version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    overwrite: true
hooks:
  BeforeInstall:
    - location: stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
